#include "idl_types.h"
//
// [
//   uuid("f5cc5a18-4264-101a-8c59-08002b2f8426"),
//   endpoint("ncacn_np:[\\pipe\\exchange_nsp]", "ncacn_ip_tcp:"),
//   pointer_default(unique),
//   version(56.0),
//   helpstring("Exchange 5.5 Name Service Provider"),
//   helper("ndr_mapi.h")
// ] interface nspi
// {
//
// https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-nspi/2554418c-a060-473a-950a-e009a53e33d9
// import "ms-dtyp.idl";

[
 uuid("F5CC5A18-4264-101A-8C59-08002B2F8426"),
 helpstring("Exchange Name Service Provider"),
 version(56.0)
//   helper("ndr_mapi.h")
]

interface nspi {
// #include "mapitags_enum.h"
// #include "mapicodes_enum.h"


  typedef struct _FILETIME {
    DWORD dwLowDateTime;
    DWORD dwHighDateTime;
  } FILETIME;

  typedef struct {
    uint8 ab[16];
  } FlatUID_r;

  typedef struct PropertyTagArray_r {
    DWORD cValues;
    [range(0, 100001)]
[size_is(cValues + 1),
length_is(cValues)] DWORD aulPropTag[];
  } PropertyTagArray_r;

  typedef struct Binary_r {
    [range(0, 2097152)] DWORD cb;
    [size_is(cb)] uint8 * lpb;
  } Binary_r;

  typedef struct ShortArray_r {
    [range(0, 100000)] DWORD cValues;
    [size_is(cValues)] uint16 * lpi;
  } ShortArray_r;

  typedef struct _LongArray_r {
    [range(0, 100000)] DWORD cValues;
    [size_is(cValues)] long * lpl;
  } LongArray_r;

  typedef struct _StringArray_r {
    [range(0, 100000)] DWORD cValues;
    [size_is(cValues)] [string] char ** lppszA;
  } StringArray_r;

  typedef struct _BinaryArray_r {
    [range(0, 100000)] DWORD cValues;
    [size_is(cValues)] Binary_r * lpbin;
  } BinaryArray_r;

  typedef struct _FlatUIDArray_r {
    [range(0, 100000)] DWORD cValues;
    [size_is(cValues)] FlatUID_r** lpguid;
  } FlatUIDArray_r;

  typedef struct _WStringArray_r {
    [range(0, 100000)] DWORD cValues;
    [size_is(cValues)] [string] uint16 ** lppszW;
  } WStringArray_r;

  typedef struct _DateTimeArray_r {
    [range(0, 100000)] DWORD cValues;
    [size_is(cValues)] FILETIME * lpft;
  } DateTimeArray_r;

  typedef struct _PropertyValue_r PropertyValue_r;

  typedef struct _PropertyRow_r {
    DWORD Reserved;
    [range(0, 100000)] DWORD cValues;
    [size_is(cValues)] PropertyValue_r * lpProps;
  } PropertyRow_r;

  typedef struct _PropertyRowSet_r {
    [range(0, 100000)] DWORD cRows;
    [size_is(cRows)] PropertyRow_r aRow[];
  } PropertyRowSet_r;

  typedef struct _Restriction_r Restriction_r;

  // typedef struct _AndOrRestriction_r {
  //   [range(0, 100000)] DWORD cRes;
  //   [size_is(cRes)] Restriction_r * lpRes;
  // } AndRestriction_r, OrRestriction_r;

  typedef struct {
      [range(0, 100000)] DWORD cRes;
      [size_is(cRes)] Restriction_r * lpRes;
  } AndRestriction_r;

  typedef struct {
      [range(0, 100000)] DWORD cRes;
      [size_is(cRes)] Restriction_r * lpRes;
  } OrRestriction_r;

  typedef struct _NotRestriction_r {
    Restriction_r * lpRes;
  } NotRestriction_r;

  typedef struct _ContentRestriction_r {
    DWORD ulFuzzyLevel;
    DWORD ulPropTag;
    PropertyValue_r * lpProp;
  } ContentRestriction_r;

  typedef struct _BitMaskRestriction_r {
    DWORD relBMR;
    DWORD ulPropTag;
    DWORD ulMask;
  } BitMaskRestriction_r;

  typedef struct _PropertyRestriction_r {
    DWORD relop;
    DWORD ulPropTag;
    PropertyValue_r * lpProp;
  } PropertyRestriction_r;

  typedef struct _ComparePropsRestriction_r {
    DWORD relop;
    DWORD ulPropTag1;
    DWORD ulPropTag2;
  } ComparePropsRestriction_r;

  typedef struct _SubRestriction_r {
    DWORD ulSubObject;
    Restriction_r * lpRes;
  } SubRestriction_r;

  typedef struct _SizeRestriction_r {
    DWORD relop;
    DWORD ulPropTag;
    DWORD cb;
  } SizeRestriction_r;

  typedef struct _ExistRestriction_r {
    DWORD ulReserved1;
    DWORD ulPropTag;
    DWORD ulReserved2;
  } ExistRestriction_r;

  typedef [v1_enum] enum {
  	RES_AND			= 0,
  	RES_OR			= 1,
  	RES_NOT			= 2,
  	RES_CONTENT		= 3,
  	RES_PROPERTY		= 4,
  	RES_COMPAREPROPS	= 5,
  	RES_BITMASK		= 6,
  	RES_SIZE		= 7,
  	RES_EXIST		= 8,
  	RES_SUBRESTRICTION	= 9,
  	RES_COMMENT		= 10
  } nspi_RestrictionType;


  typedef [switch_type(nspi_RestrictionType)] union _RestrictionUnion_r {
    [case (RES_AND)] AndRestriction_r resAnd;
    [case (RES_OR)] OrRestriction_r resOr;
    [case (RES_NOT)] NotRestriction_r resNot;
    [case (RES_CONTENT)] ContentRestriction_r resContent;
    [case (RES_PROPERTY)] PropertyRestriction_r resProperty;
    [case (RES_COMPAREPROPS)] ComparePropsRestriction_r resCompareProps;
    [case (RES_BITMASK)] BitMaskRestriction_r resBitMask;
    [case (RES_SIZE)] SizeRestriction_r resSize;
    [case (RES_EXIST)] ExistRestriction_r resExist;
    [case (RES_SUBRESTRICTION)] SubRestriction_r resSubRestriction;
  } RestrictionUnion_r;

  struct _Restriction_r {
    DWORD rt;
    [switch_is((long)rt)] RestrictionUnion_r res;
  };

  typedef struct PropertyName_r {
    FlatUID_r * lpguid;
    DWORD ulReserved;
    long lID;
  } PropertyName_r;

  typedef struct PropertyNameSet_r {
    [range(0, 100000)] DWORD cNames;
    [size_is(cNames)] PropertyName_r aNames[];
  } PropertyNameSet_r;

  typedef struct _StringsArray {
    [range(0, 100000)] DWORD Count;
    [size_is(Count)] [string] char * Strings[];
  } StringsArray_r;


  typedef struct _WStringsArray {
    [range(0, 100000)] DWORD Count;
    [size_is(Count)] [string] uint16 * Strings[];
  } WStringsArray_r;

  typedef struct _STAT {
    DWORD SortType;
    DWORD ContainerID;
    DWORD CurrentRec;
    long Delta;
    DWORD NumPos;
    DWORD TotalRecs;
    DWORD CodePage;
    DWORD TemplateLocale;
    DWORD SortLocale;
  }STAT;

  typedef [v1_enum] enum {
  	PT_UNSPECIFIED	= 0x0000,
  	PT_NULL		= 0x0001,
  	PT_I2		= 0x0002,
  	PT_LONG		= 0x0003,
  	PT_R4		= 0x0004,
  	PT_DOUBLE	= 0x0005,
  	PT_CURRENCY	= 0x0006,
  	PT_APPTIME	= 0x0007,
  	PT_ERROR	= 0x000a,	/* means the given attr contains no value */
  	PT_BOOLEAN	= 0x000b,
  	PT_OBJECT	= 0x000d,
  	PT_I8		= 0x0014,
  	PT_STRING8	= 0x001e,
  	PT_UNICODE	= 0x001f,
  	PT_SYSTIME	= 0x0040,
  	PT_CLSID	= 0x0048,
  	PT_BINARY	= 0x0102,

  	/* Multi-valued properties */

  	PT_MV_I2	= 0x1002,
  	PT_MV_LONG	= 0x1003,
  	PT_MV_R4	= 0x1004,
  	PT_MV_DOUBLE	= 0x1005,
  	PT_MV_CURRENCY	= 0x1006,
  	PT_MV_APPTIME	= 0x1007,
  	PT_MV_I8	= 0x1014,
  	PT_MV_STRING8	= 0x101e,
  	PT_MV_TSTRING	= 0x101e,
  	PT_MV_UNICODE	= 0x101f,
  	PT_MV_SYSTIME	= 0x1040,
  	PT_MV_CLSID	= 0x1048,
  	PT_MV_BINARY	= 0x1102
  } property_types;


  typedef [switch_type(long)] union _PV_r {
    [case (PT_I2)] uint16 i;
    [case (PT_LONG)] long l;
    [case (PT_BOOLEAN)] uint16 b;
    [case (PT_STRING8)] [string] char * lpszA;
    [case (PT_BINARY)] Binary_r bin;
    [case (PT_UNICODE)] [string] uint16 * lpszW;
    [case (PT_CLSID)] FlatUID_r * lpguid;
    [case (PT_SYSTIME)] FILETIME ft;
    [case (PT_ERROR)] long err;
    [case (PT_MV_I2)] ShortArray_r MVi;
    [case (PT_MV_LONG)] LongArray_r MVl;
    [case (PT_MV_TSTRING)] StringArray_r MVszA;
    [case (PT_MV_BINARY)] BinaryArray_r MVbin;
    [case (PT_MV_CLSID)] FlatUIDArray_r MVguid;
    [case (PT_MV_UNICODE)] WStringArray_r MVszW;
    [case (PT_MV_SYSTIME)] DateTimeArray_r MVft;
    [case (PT_NULL)] long lReserved1;
    [case (PT_OBJECT)] long lReserved2;
  } PROP_VAL_UNION;

  struct _PropertyValue_r {
    DWORD ulPropTag;
    DWORD ulReserved;
    [switch_is ((long)(ulPropTag & 0x0000FFFF))]
PROP_VAL_UNION Value;
  };

#if 0
	/*
	 * pidl does not yet have a real [context_handle] implementation, so we
	 * just use some defines here.
	 */

  typedef [context_handle] void *NSPI_HANDLE;
#else
#define NSPI_HANDLE policy_handle
#endif




//opnum 0
DWORD
   NspiBind(
     // [in] handle_t hRpc,
     [in] uint64 hRpc,
     [in] DWORD dwFlags,
     [in] STAT * pStat,
     [in,out,unique] FlatUID_r * pServerGuid,
     [out,ref] NSPI_HANDLE * contextHandle
     );

//opnum 1
DWORD
    NspiUnbind(
       [in,out] NSPI_HANDLE * contextHandle,
       [in] DWORD Reserved
       );

  //opnum 2
  DWORD
    NspiUpdateStat(
   [in] NSPI_HANDLE hRpc,
   [in] DWORD Reserved,
   [in,out] STAT * pStat,
   [in,out,unique] long * plDelta
   );

  //opnum 3
  DWORD
    NspiQueryRows(
  [in] NSPI_HANDLE hRpc,
  [in] DWORD dwFlags,
  [in, out] STAT * pStat,
  [in, range(0, 100000)] DWORD dwETableCount,
  [in, unique, size_is(dwETableCount)] DWORD * lpETable,
  [in] DWORD Count,
  [in,unique] PropertyTagArray_r * pPropTags,
  [out] PropertyRowSet_r ** ppRows
  );

  //opnum 4
  DWORD
    NspiSeekEntries(
    [in] NSPI_HANDLE hRpc,
    [in] DWORD Reserved,
    [in,out] STAT * pStat,
    [in] PropertyValue_r * pTarget,
    [in, unique] PropertyTagArray_r * lpETable,
    [in,unique] PropertyTagArray_r * pPropTags,
    [out] PropertyRowSet_r ** ppRows
    );

  //opnum 5
  DWORD
    NspiGetMatches(
   [in] NSPI_HANDLE hRpc,
   [in] DWORD Reserved1,
   [in,out] STAT * pStat,
   [in, unique] PropertyTagArray_r * pReserved,
   [in] DWORD Reserved2,
   [in,unique] Restriction_r * Filter,
   [in,unique] PropertyName_r * lpPropName,
   [in] DWORD ulRequested,
   [out] PropertyTagArray_r ** ppOutMIds,
   [in,unique] PropertyTagArray_r * pPropTags,
   [out] PropertyRowSet_r ** ppRows
   );

  //opnum 6
  DWORD
    NspiResortRestriction(
  [in] NSPI_HANDLE hRpc,
  [in] DWORD Reserved,
  [in,out] STAT * pStat,
  [in] PropertyTagArray_r * pInMIds,
  [in,out] PropertyTagArray_r ** ppOutMIds
  );

  //opnum 7
  DWORD
    NspiDNToMId(
[in] NSPI_HANDLE hRpc,
[in] DWORD Reserved,
[in] StringsArray_r * pNames,
[out] PropertyTagArray_r ** ppOutMIds
);

  //opnum 8
  DWORD
     NspiGetPropList(
    [in] NSPI_HANDLE hRpc,
    [in] DWORD dwFlags,
    [in] DWORD dwMId,
    [in] DWORD CodePage,
    [out] PropertyTagArray_r ** ppPropTags
    );

  //opnum 9
  DWORD
    NspiGetProps(
 [in] NSPI_HANDLE hRpc,
 [in] DWORD dwFlags,
 [in] STAT * pStat,
 [in,unique] PropertyTagArray_r * pPropTags,
 [out] PropertyRow_r ** ppRows
 );

  //opnum 10
  DWORD
    NspiCompareMIds(
    [in] NSPI_HANDLE hRpc,
    [in] DWORD Reserved,
    [in] STAT * pStat,
    [in] DWORD MId1,
    [in] DWORD MId2,
    [out] long * plResult
    );

  //opnum 11
  DWORD
    NspiModProps(
    [in] NSPI_HANDLE hRpc,
    [in] DWORD Reserved,
    [in] STAT * pStat,
    [in, unique] PropertyTagArray_r * pPropTags,
    [in] PropertyRow_r * pRow
    );

  //opnum 12
  DWORD
    NspiGetSpecialTable(
   [in] NSPI_HANDLE hRpc,
   [in] DWORD dwFlags,
   [in] STAT * pStat,
   [in, out] DWORD * lpVersion,
   [out] PropertyRowSet_r ** ppRows
   );

  //opnum 13
  DWORD
    NspiGetTemplateInfo(
   [in] NSPI_HANDLE hRpc,
   [in] DWORD dwFlags,
   [in] DWORD ulType,
   [in,unique] [string] char * pDN,
   [in] DWORD dwCodePage,
   [in] DWORD dwLocaleID,
   [out] PropertyRow_r ** ppData
);

  //opnum 14
  DWORD
    NspiModLinkAtt(
    [in] NSPI_HANDLE hRpc,
    [in] DWORD dwFlags,
    [in] DWORD ulPropTag,
    [in] DWORD dwMId,
    [in] BinaryArray_r * lpEntryIds
    );

  //opnum 15
  DWORD
   Opnum15NotUsedOnWire(
      [in] NSPI_HANDLE Reserved1,
      [in] DWORD Reserved2,
      [in] DWORD Reserved3,
      [in] BinaryArray_r * Reserved4
      );

  //opnum 16
  DWORD
    NspiQueryColumns(
     [in] NSPI_HANDLE hRpc,
     [in] DWORD Reserved,
     [in] DWORD dwFlags,
     [out] PropertyTagArray_r ** ppColumns
     );

  //opnum 17
  DWORD
    NspiGetNamesFromIDs(
   [in] NSPI_HANDLE hRpc,
   [in] DWORD Reserved,
   [in, unique] FlatUID_r * lpguid,
   [in, unique] PropertyTagArray_r * pPropTags,
   [out] PropertyTagArray_r ** ppReturnedPropTags,
   [out] PropertyNameSet_r ** ppNames
   );

  //opnum 18
  DWORD
    NspiGetIDsFromNames(
   [in] NSPI_HANDLE hRpc,
   [in] DWORD Reserved,
   [in] DWORD dwFlags,
   [in, range(0, 100000)] DWORD cPropNames,
   [in, size_is(cPropNames)] PropertyName_r ** pNames,
   [out] PropertyTagArray_r ** ppPropTags
   );

  //opnum 19
  DWORD
    NspiResolveNames(
     [in] NSPI_HANDLE hRpc,
     [in] DWORD Reserved,
     [in] STAT * pStat,
     [in, unique] PropertyTagArray_r * pPropTags,
     [in] StringsArray_r * paStr,
     [out] PropertyTagArray_r ** ppMIds,
     [out] PropertyRowSet_r ** ppRows
     );

  //opnum 20
  DWORD
    NspiResolveNamesW(
      [in] NSPI_HANDLE hRpc,
      [in] DWORD Reserved,
      [in] STAT * pStat,
      [in, unique] PropertyTagArray_r * pPropTags,
      [in] WStringsArray_r * paWStr,
      [out] PropertyTagArray_r ** ppMIds,
      [out] PropertyRowSet_r ** ppRows
      );

}

